// Code generated by go-swagger; DO NOT EDIT.

package other

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostSignupHandlerFunc turns a function with the right signature into a post signup handler
type PostSignupHandlerFunc func(PostSignupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostSignupHandlerFunc) Handle(params PostSignupParams) middleware.Responder {
	return fn(params)
}

// PostSignupHandler interface for that can handle valid post signup params
type PostSignupHandler interface {
	Handle(PostSignupParams) middleware.Responder
}

// NewPostSignup creates a new http.Handler for the post signup operation
func NewPostSignup(ctx *middleware.Context, handler PostSignupHandler) *PostSignup {
	return &PostSignup{Context: ctx, Handler: handler}
}

/*
	PostSignup swagger:route POST /signup Other postSignup

Регистрация пользователя
*/
type PostSignup struct {
	Context *middleware.Context
	Handler PostSignupHandler
}

func (o *PostSignup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostSignupParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostSignupOKBody post signup o k body
//
// swagger:model PostSignupOKBody
type PostSignupOKBody struct {

	// user guid
	// Format: uuid
	UserGUID strfmt.UUID `json:"user_guid,omitempty"`
}

// Validate validates this post signup o k body
func (o *PostSignupOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateUserGUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostSignupOKBody) validateUserGUID(formats strfmt.Registry) error {
	if swag.IsZero(o.UserGUID) { // not required
		return nil
	}

	if err := validate.FormatOf("postSignupOK"+"."+"user_guid", "body", "uuid", o.UserGUID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post signup o k body based on context it is used
func (o *PostSignupOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostSignupOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostSignupOKBody) UnmarshalBinary(b []byte) error {
	var res PostSignupOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
